### ISSUE TITLE
PW-Manager ToDo

### ISSUE THREAD

**Issue by CyberAI** [hulu8004/PWManager#1]
**User System**:

**Server Management**:
- [ ] Turn on and off maps from pwManager

**Account Management**:
- [ ] Register Accounts
- [ ] Ban Accounts
- [ ] Grant elevated access to accounts (GM)
- [ ] List Accounts
- [ ] List Characters on accounts
- [ ] Grant pwManager access to accounts

**Character Management**:
- [ ] Character List, this is a collection of all the characters for all accounts
- [ ] Character XML Editor
- [ ] Inventory Editor
- [ ] Delete Characters
- [ ] Rename Characters

**Server Information**:
- [ ] Display system RAM usage
- [ ] Display system information such as storage space?

**Mailing System**:
- [ ] Send mail and items via mail in game
- [ ] Send emails to accounts registered with emails

**Chat System**:
- [ ] Chat Live with players in game
- [ ] Chat System in pwManager?

**Ticket System**:
- [ ] Normal Users can submit a ticket, Elevated Users can view and respond to them

Note taking capabilities.
